### PR TITLE
Vsi from volume

### PR DESCRIPTION
**Pull request by deepaksibm**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Review by astha-jain — COMMENTED** [review]
Question: Why do I see vpc classic?

**Comment by deepaksibm** [comment]
PROD us-south acceptance test results



`
$ tfpt TestAccIBMISInstance_ByVolume
=== RUN   TestAccIBMISInstance_ByVolume
no message sent
no message sent
no message sent
no message sent
no message sent
no message sent
--- PASS: TestAccIBMISInstance_ByVolume (344.42s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     345.971s

$ tfpt TestAccIBMISInstance_basic
=== RUN   TestAccIBMISInstance_basic
no message sent
no message sent
no message sent
no message sent
--- PASS: TestAccIBMISInstance_basic (253.49s)
=== RUN   TestAccIBMISInstance_basicwithipv4
no message sent
no message sent
no message sent
no message sent
--- PASS: TestAccIBMISInstance_basicwithipv4 (172.82s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     427.281s

$ tfpt TestAccIBMISInstance_ResizeBoot
=== RUN   TestAccIBMISInstance_ResizeBoot
no message sent
no message sent
--- PASS: TestAccIBMISInstance_ResizeBoot (208.33s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     209.336s

$ tfpt TestAccIBMISInstance_bootVolumeUserTags
=== RUN   TestAccIBMISInstance_bootVolumeUserTags
no message sent
no message sent
--- PASS: TestAccIBMISInstance_bootVolumeUserTags (232.46s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     233.659s


$ tfpt TestAccIBMISInstanceSnapshotRestore_basic
=== RUN   TestAccIBMISInstanceSnapshotRestore_basic
no message sent
no message sent
no message sent
no message sent
no message sent
--- PASS: TestAccIBMISInstanceSnapshotRestore_basic (281.98s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     282.926s`

**Comment by deepaksibm** [comment]
```

resource "ibm_is_subnet" "subnet1" {
  name                     = "tfp-subnet4"
  vpc                      = ibm_is_vpc.vpc1.id
  zone                     = "us-south-2"
  total_ipv4_address_count = 16
  
}
resource "ibm_is_vpc" "vpc1" {
  name                      = "tfp-test"
  address_prefix_management = "auto"
}
resource "ibm_is_instance" "example1" {  
  name    = "tfp-bug-test"  
  profile = "bx2-8x32"  

  image = "r006-0c832417-8b49-41ab-94ce-63c229a5d197" // prod
  primary_network_interface {    
    subnet                    = ibm_is_subnet.subnet1.id
    name                      = "tfp-primary-interface"  
    //security_groups = [ibm_is_security_group.vpn_server_security_group.id]
  }  
  vpc  = ibm_is_subnet.subnet1.vpc
  zone = "us-south-2"
  keys = [ibm_is_ssh_key.sshkey.id]  
}
resource "ibm_is_snapshot" "example1" {
  name          = "example-snapshot-boot"
  source_volume = ibm_is_instance.example1.boot_volume[0].volume_id

  //User can configure timeouts
  timeouts {
    create = "15m"
    delete = "15m"
  }
}


resource "ibm_is_volume" "example" {
  name            = "example-volume"
  profile         = "10iops-tier"
  zone            = "us-south-2"
  source_snapshot = ibm_is_snapshot.example1.id
}

resource "ibm_is_instance" "example" {
  name    = "example-vsi-fvolume"
  profile = "cx2-2x4"
  boot_volume {
    volume_id = ibm_is_volume.example.id
  }
  primary_network_interface {
    subnet = ibm_is_subnet.subnet1.id
  }
  vpc  = ibm_is_vpc.vpc1.id
  zone = "us-south-2"
  keys = [ibm_is_ssh_key.sshkey.id]
  network_interfaces {
    subnet = ibm_is_subnet.subnet1.id
    name   = "eth1"
  }
}
```

**Comment by deepaksibm** [comment]
upstream merged

**Pull request closed without merging**
