### PR TITLE
Enterprise sharing image

### PR DESCRIPTION
**Pull request by ujjwal-ibm**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
=== RUN   TestAccIBMISInstanceTemplate_catalog_basic
--- PASS: TestAccIBMISInstanceTemplate_catalog_basic (139.00s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     141.027s
```
```
=== RUN   TestAccIBMISInstanceTemplate_data_catalog
--- PASS: TestAccIBMISInstanceTemplate_data_catalog (136.41s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     138.240s
```
```
=== RUN   TestAccIBMISInstanceTemplates_dataCatalog
--- PASS: TestAccIBMISInstanceTemplates_dataCatalog (132.51s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     135.455s
```

### CODE REVIEW

**Comment by ujjwal-ibm** [comment]
```
=== RUN   TestAccIBMISInstanceTemplate_catalog_basic
--- PASS: TestAccIBMISInstanceTemplate_catalog_basic (134.09s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     136.012s
```

**Comment by ujjwal-ibm** [comment]
```
=== RUN   TestAccIBMISInstanceTemplate_data_catalog
--- PASS: TestAccIBMISInstanceTemplate_data_catalog (142.43s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     144.017s
```

**Comment by ujjwal-ibm** [comment]
```
=== RUN   TestAccIBMISInstanceTemplates_dataCatalog
--- PASS: TestAccIBMISInstanceTemplates_dataCatalog (131.50s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     133.040s
```

**Comment by BShrivastav** [comment]
Working as expected.

**Comment by BShrivastav** [comment]
Working as expected.

**Comment by ujjwal-ibm** [comment]
moving to upstream

**Pull request closed without merging**
