### PR TITLE
fix(bare_metal_server_network_interface_allow_float) : reordered the wait logic in bare metal nics

### PR DESCRIPTION
**Pull request by ujjwal-ibm**
…

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by SunithaGudisagarIBM** [comment]
Screenshot 2022-10-11 at 2 13 16 PM

**Comment by SunithaGudisagarIBM** [comment]
image

**Comment by SunithaGudisagarIBM** [comment]
Had one review comment and is resolved now..
PR is good to go..

Thank you

**Review by BShrivastav — APPROVED** [review]

**Comment by ujjwal-ibm** [comment]
moved to upstream

**Pull request closed without merging**
