### PR TITLE
enhancement(profiles): added support for vcpu manufacturer(vsi, dh)

### PR DESCRIPTION
**Pull request by BShrivastav**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
=== RUN   TestAccIbmIsDedicatedHostProfilesDataSourceBasic
--- PASS: TestAccIbmIsDedicatedHostProfilesDataSourceBasic (36.21s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     38.499s
```

```
=== RUN   TestAccIbmIsDedicatedHostProfileDataSourceBasic
--- PASS: TestAccIbmIsDedicatedHostProfileDataSourceBasic (24.96s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     26.647s
```
```
=== RUN   TestAccIBMISInstanceProfilesDataSource_basic
--- PASS: TestAccIBMISInstanceProfilesDataSource_basic (36.06s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     38.119s
```
```
--- PASS: TestAccIBMISInstanceProfileDataSource_basic (41.39s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     44.007s
```
```
--- PASS: TestAccIBMISInstanceDataSource_basic (325.61s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     327.791s
```
```
=== RUN   TestAccIBMISInstancesDataSource_basic
no message sent
no message sent
--- PASS: TestAccIBMISInstancesDataSource_basic (216.74s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     218.425s
```
```
=== RUN   TestAccIBMISInstance_basic
no message sent
no message sent
no message sent
no message sent
--- PASS: TestAccIBMISInstance_basic (283.59s)
=== RUN   TestAccIBMISInstance_basicwithipv4
no message sent
no message sent
--- PASS: TestAccIBMISInstance_basicwithipv4 (156.41s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     441.875s
```

### CODE REVIEW

**Comment by SunithaGudisagarIBM1** [comment]
```
data "ibm_is_image" "example" {
 name = "ibm-ubuntu-22-04-1-minimal-amd64-4"
}
resource "ibm_is_vpc" "testacc_vpc" {
	name = "sunitha-tfp-vpc"
}

resource "ibm_is_subnet" "testacc_subnet" {
	name                      = "sunitha-tfp-subnet"
	vpc                       = ibm_is_vpc.testacc_vpc.id
	zone                      = "us-south-1"
  total_ipv4_address_count  = 16
}
	  
resource "ibm_is_ssh_key" "testacc_sshkey" {
	name       			= "sunitha-tfp-ssh"
	public_key 			= file("~/.ssh/id_rsa.pub")
}

resource "ibm_is_instance" "testacc_instance" {
	name   				= "sunitha-tfp-vsi"
	profile 			= "bx2-2x8"
  	image = data.ibm_is_image.example.id
	primary_network_interface {
		subnet = ibm_is_subnet.testacc_subnet.id
	}
	vpc     = ibm_is_vpc.testacc_vpc.id
	zone    = ibm_is_subnet.testacc_subnet.zone
	keys    = [ibm_is_ssh_key.testacc_sshkey.id]
}
data ibm_is_instance this {
	name = "sunitha-tfp-vsi"
}
data ibm_is_instances this {
	
}
```
Screenshot 2023-06-19 at 11 10 27 AM
Screenshot 2023-06-19 at 11 12 01 AM

**Comment by SunithaGudisagarIBM1** [comment]
This PR is ready to move to upstream

**Comment by ujjwal-ibm** [comment]
moving to upstream

**Comment by ujjwal-ibm** [comment]
also have made a change in ibm/acctest/acctest.go file, updated the image name, so its showing +2 changes on upstream

**Pull request closed without merging**
